apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/part-of: app-frontend
  name: frontend
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: frontend
      app.kubernetes.io/part-of: app-frontend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: frontend
        app.kubernetes.io/part-of: app-frontend
    spec:
      containers:
      - image: jduimovich/frontend:latest
        imagePullPolicy: Always
        name: frontend
        ports:
        - containerPort: 8080 
        resources:
          limits:
            cpu: "200m"
            memory: "48Mi"
          requests:
            cpu: "100m"
            memory: "48Mi"
      serviceAccountName: default
status: {}
