apiVersion: apps/v1
kind: Deployment
metadata: 
  labels:
    app.kubernetes.io/name: fibs-service
    app.kubernetes.io/part-of: app-graphtuitous
  name: fib-go-deployment
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: fibs-service
      app.kubernetes.io/part-of: app-graphtuitous
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: fibs-service
        app.kubernetes.io/part-of: app-graphtuitous
    spec:      
      securityContext:
        runAsNonRoot: true
      containers:
      - image: jduimovich/fib-go:latest
        imagePullPolicy: Always
        name: fib-go-deployment
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "200m"
            memory: "48Mi"
          requests:
            cpu: "100m"
            memory: "32Mi"
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
        livenessProbe:
          initialDelaySeconds: 60
          periodSeconds: 5
          httpGet:
            path: /fib
            port: 8080
        securityContext:
          capabilities:
            drop:
              - all
      serviceAccountName: default
status: {}
