apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgBUhFkV3M7y5AWKTZZqg7hBej6R3EEN69n/EJ+1zzmL66xlJBCW0JzY52vwdslHz/J2Qfx2n9GjHEi1uXjWqM1ibUrRIw5SNFM/Mz0KBa7INF0BQ3Uc5UqNGpSnvRPbcaGQsqwIW1o7s5ndXXLRGqKZCGgJavdhOfrxfxbORHfCLsw0xHslHyMejTBuWUVdspYy582jKZpbOUQDpVJ8vc//wlbvRdgTpRE3EuT1EF+0bJX63nFVzskoKThKOMFMw/yBD0qlwqZOkGGXfdiAxYoI4YaIQ3WfBw/rrfhRyk8YACSLpEturuFYeoKlB8vYwGwbQ9Tq+Olgr1B4NAy0eTcZCB/wThCWRZGgqA5gItzpE5sKs7QeSUl355OLrP/koGLEndkynnOOo58GATkpAgmb+d7euk5EqEOZ8vWFkQ+GB6dYrZ5/klGdY67jwAUuTV2V1QgUdvNT6QByhUWOiqRvY/Bo8YDYpMIeOhG1N3B+e9OW8a+1TtOYJnXDRzHCkJdfWGnGQWkOWfYSkgxwcv7YKCFpaLNJNPx0dVBfgqg1BnANciRONpv9jPOr39RsnqWdaBlGgqk+ZYCp+MUV04fjVtFPV+mPjywjEyfo15I5xF12HkOiAyE6sfD5IrBluBa4ueHk8ubhnO8nfzzNcccsj3dWibwsJ1fawiBSW6CQG/pXwaIleADpCYh5JLcqjuUciPgVCAKaGwiLfe/GkaAq/HArlw==
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
