apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-haproxy
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgCU3C66oXaL5+tJ6CSFEe9ozDFX7H0aKHp1a897HU2XvOenelMsgU9nPuTJH5wlOiSSPyVk0oKKDdXCHahaVr32EXk0TIG+V06I0c+VlcJOHtVQoi2Z5Q79cfVBBpHIfpBlzhIAAYC6zHLgTUrRvuxVB8gCsBmbSUFtattmakpxaRGvezfT/+2awItWoQ0PzzF0MAUQQTjHFl2HGxAQeydnzDLMsvvGXaDYzZS9soWZ7x27N5j+LjZNLe0nRxqXoR9MHS7SBBLbHTMxBsH783gMdjFx0js+8SFlNJZsG8YfAKSo0twTsdf8EO8a2MTAt67FP3weFzJpI7tZ+SmZCXAkZk6HDI2AYk0KC/X751m+JJ/WzbIMOms3WTaRle7O3IrPlSpvdrveTYr9SeJNDAYW67nBLff47XRlmC11abf0kqpdNhEWh1Ce4RcS2tdGLc4OajDHq/xj4HcacbBsHQye7ASfYu1Xk24hb5UCQrqfhohL4nD3FHZw3H2LBher3Nmi8+WSgZg6YWEjH8EKE0pfWNri+flPTxx0Pk4rkGe6Uplj/ufaPErkNGRPeN85krMCTXuRpk4nu9PEenHJcRzj/MPxBOF87ny/wU8ruvPfy8kkeAuHuZHu0Mwy6/h1mdfB99QRuFZvwSWzDhjb7xZO2TdfBZS/AWfeln2A6K1aTjuElhqMnmHSuNiFe0oAIatVDRRP3uqtuzcMOG00zJAYyQA1iA==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-haproxy
      namespace: cicd
    type: Opaque
