apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  creationTimestamp: null
  name: cicd-event-listener
  namespace: cicd
spec:
  podTemplate: {}
  serviceAccountName: pipeline
  triggers:
  - bindings:
    - ref: github-push-binding
    interceptors:
    - github:
        secretRef:
          namespace: cicd
          secretKey: webhook-secret-key
          secretName: gitops-webhook-secret
    - cel:
        filter: (header.match('X-GitHub-Event', 'push') && body.repository.full_name == 'jduimovich/gt-app')
        overlays:
        - expression: body.ref.split('/')[2]
          key: ref
    name: ci-dryrun-from-push
    template:
      name: ci-dryrun-from-push-template
  - bindings:
    - ref: dev-app-haproxy-haproxy-binding
    - ref: github-push-binding
    interceptors:
    - github:
        secretRef:
          namespace: cicd
          secretKey: webhook-secret-key
          secretName: webhook-secret-dev-haproxy
    - cel:
        filter: (header.match('X-GitHub-Event', 'push') && body.repository.full_name == 'jduimovich/haproxy')
        overlays:
        - expression: body.ref.split('/')[2]
          key: ref
    name: app-ci-build-from-push-haproxy
    template:
      name: app-ci-template
status:
  configuration:
    generatedName: ""
