apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: haproxy
    app.kubernetes.io/part-of: app-graphtuitous
    app.openshift.io/runtime : haproxy 
  name: haproxy
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: haproxy
      app.kubernetes.io/part-of: app-graphtuitous
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: haproxy
        app.kubernetes.io/part-of: app-graphtuitous
    spec:
      containers:
      - image: jduimovich/haproxy:latest
        imagePullPolicy: Always
        name: haproxy
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "200m"
            memory: "128Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
      serviceAccountName: default
status: {}
