apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: haproxy
    app.kubernetes.io/part-of: app-haproxy
  name: haproxy
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: haproxy
      app.kubernetes.io/part-of: app-haproxy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: haproxy
        app.kubernetes.io/part-of: app-haproxy
    spec:
      containers:
      - image: jduimovich/fib-go:latest
        imagePullPolicy: Always
        name: haproxy
        ports:
        - containerPort: 8080
        resources: {}
      serviceAccountName: default
status: {}
