apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: fibs-service
    app.kubernetes.io/part-of: app-frontend
  name: fib-go-deployment
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: fibs-service
      app.kubernetes.io/part-of: app-frontend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: fibs-service
        app.kubernetes.io/part-of: app-frontend
    spec:
      containers:
      - image: jduimovich/fib-go:latest
        imagePullPolicy: Always
        name: fib-go-deployment
        ports:
        - containerPort: 8080
        resources: {}
      serviceAccountName: default
status: {}
